apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dipaiwin/gitops-cert-level-2-examples
    targetRevision: master
    path: ./simple-application
  destination:
    server: https://kubernetes.default.svc
    namespace: caster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
